
build:
    environment:
        variables:
            JWT_SECRET: 'jwtSecret'
    nodes:
        coverage:
            tests:
                override:
                    - command: npm test
                      coverage:
                          file: coverage/clover.xml
                          format: clover
